#pragma once

#define NEST_VERSION_MAJOR 0
#define NEST_VERSION_MINOR 1
#define NEST_VERSION_PATCH 0

#define NEST_VERSION (NEST_VERSION_PATCH + NEST_VERSION_MINOR * 100 + NEST_VERSION_MAJOR + 100000)
